Add namespaces and remove unused data
Catel/Catel.Templates pull request #61
Opened 2020-06-28 09:08 UTC by abrca

### Description of Change ###

Namespace is automatically added to a using directive at the beginning of the code if it doesn't already exist.
Remove unused Literals

### Issues Resolved ### 

None

### API Changes ###
 
None

### Platforms Affected ### 

- All

### Behavioral Changes ###

None

### Testing Procedure ###

### PR Checklist ###

- [ ] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

2020-06-28 09:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Catel/Catel.Templates?pullRequest=61) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Catel/Catel.Templates?pullRequest=61) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Catel/Catel.Templates?pullRequest=61) it.</sub>

2020-06-29 05:08 UTC, GeertvanHorrik requested changes
Fantastic PR, thanks for the great improvements. Please see the comments and double check whether they make sense.

2020-06-29 05:08 UTC, GeertvanHorrik commented on snippets/C#/vmtaskcommand.snippet
> +                    <Namespace>Catel.MVVM</Namespace>
Shouldn't this one also import System.Threading.Tasks?

2020-06-29 05:08 UTC, GeertvanHorrik commented on snippets/C#/vmtaskcommandwithcanexecute.snippet
> +                    <Namespace>Catel.MVVM</Namespace>
Shouldn't this one also import System.Threading.Tasks?

2020-06-29 14:33 UTC, abrca commented
You are right, I'll fix it.

And I have a question about model.snippet.
It use '#if NET', and this symbol is defined in \templates\C#\ProjectTemplates\Catel.WPF.Application\Catel.WPF.Application.csproj as synonym to .NET Framework target.
Keep it, assuming that people using this snippets will also use this project template, or replace it with more correct '#if NETFRAMEWORK || NETCOREAPP || NETSTANDARD', as in Catel.Core\Data\ModelBase.cs ?

2020-06-29 14:59 UTC, GeertvanHorrik commented
I think the serialization constructor (at least for 6.0) can be removed. And since we are moving towards a single .NET anyway, I think it's wise to remove the #if as a while and just put the `Serializable` interface there. Agree?

2020-06-29 15:05 UTC, abrca commented
Yes, good idea.

2020-06-30 13:17 UTC, GeertvanHorrik commented
looks fantastic, thanks!

2020-06-30 13:17 UTC, merged

2020-06-30 14:01 UTC, GeertvanHorrik commented
see https://marketplace.visualstudio.com/items?itemName=Catel.Catel-CodeSnippets

2020-06-30 14:05 UTC, abrca commented
It might be better to split tag to two - 'catel' and 'snippets' ?

2020-06-30 14:07 UTC, GeertvanHorrik commented
Excellent point, re-releasintg